/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.BillDAO;
import DAO.BillInfoDAO;
import DAO.CategoryDAO;
import DAO.DrinksDAO;
import DAO.OrderNumberDAO;
import DAO.StorageDAO;
import Helper.DialogHelper;
import Helper.JdbcHelper;
import Helper.ShareHelper;
import Model.Category;
import Model.Drinks;
import Model.OrderNumber;
import Model.Storage;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import keeptoo.KButton;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.FontMetrics;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author Huy Thinh
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        load();
        DefaultTableModel model2 = (DefaultTableModel) tblBill.getModel();
        model2.setRowCount(0);
        loadtable();
        setname();
    }
    BillDAO bdao = new BillDAO();
    BillInfoDAO bidao = new BillInfoDAO();
    OrderNumberDAO ordao = new OrderNumberDAO();
    int total = 0;
    List<Object[]> listobj = new ArrayList<>();
    List<Object[]> listbill = new ArrayList<>();

    void setname() {
        if (ShareHelper.USER.isRole()) {
            lblname.setText("Nhân viên:" + ShareHelper.USER.getDisplayName());
        } else {
            lblname.setText("Quản lý:" + ShareHelper.USER.getDisplayName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JTextField();
        txtOrderNumber = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbl22222 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        pnlCate = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tabOrder = new javax.swing.JTabbedPane();
        pnlMenu = new javax.swing.JPanel();
        pnlOrder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 102));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Website-1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 340));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "CATE", "PRICE", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBill.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane2.setViewportView(tblBill);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 370));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PHONE");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ORDER NUMBER");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 110, 40));
        jPanel6.add(txtCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 300, 40));

        txtOrderNumber.setText("1");
        jPanel6.add(txtOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 300, 40));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 410, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 410, 90));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-money-bag-50.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(91, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-edit-50.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(91, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(91, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-broom-50.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setPreferredSize(new java.awt.Dimension(91, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 410, 70));

        lbl22222.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        lbl22222.setForeground(new java.awt.Color(255, 255, 255));
        lbl22222.setText("Total");
        jPanel5.add(lbl22222, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, 30));

        lbTotal.setBackground(new java.awt.Color(255, 255, 255));
        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 130, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 410, 560));

        pnlCate.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.add(pnlCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 340, 520));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 500, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 570, 30));

        tabOrder.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N

        pnlMenu.setBackground(new java.awt.Color(153, 153, 0));
        tabOrder.addTab("Menu", pnlMenu);

        pnlOrder.setBackground(new java.awt.Color(153, 153, 0));
        tabOrder.addTab("Order ", pnlOrder);

        jPanel1.add(tabOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 570, 530));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setText("Admin - Huy Thịnh");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 340, 40));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1341, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        list = drdao.ShowDrinks(jTextField1.getText());
        pnlMenu.removeAll();
        pnlMenu.revalidate();
        pnlMenu.repaint();
        loadtable();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtCustomerPhone.getText().length() == 0) {
                if (AccountManage.isNumberic(txtOrderNumber.getText()) == true) {
                    bdao.insert(Integer.parseInt(txtOrderNumber.getText()), lblname.getText(), null, total);
                } else {
                    DialogHelper.alert(this, "Nhập số order");
                }
            } else if (AccountManage.isNumberic(txtCustomerPhone.getText())!=true) {
                DialogHelper.alert(this, "Vui lòng nhập số k nhập chữ");
            } else {
                try {
                    if (AccountManage.isNumberic(txtOrderNumber.getText()) == true) {
                        bdao.insert(Integer.parseInt(txtOrderNumber.getText()), lblname.getText(), txtCustomerPhone.getText(), total);
                    } else {
                        DialogHelper.alert(this, "Nhập số order");
                    }
                } catch (Exception e) {
                    DialogHelper.alert(this, "Số điện thoại k tồn tại");
                }
            }
            for (Object[] object : listobj) {
                int idbill = bdao.maxbill(0);
                int iddrink = (int) object[0];
                int quantity = (int) object[4];
                Float price = Float.parseFloat(String.valueOf(object[3]).substring(0, String.valueOf(object[3]).length() - 2)) * (int) object[4];
                bidao.insert(idbill, iddrink, quantity, price);
                ordao.Update(new OrderNumber(Integer.parseInt(txtOrderNumber.getText()), true));
                StorageDAO stdao = new StorageDAO();
                List<Storage> sto = stdao.findbyid(iddrink);
                Storage st = new Storage(sto.get(0).getId(), sto.get(0).getQuantity() - quantity);
                stdao.update(st);
            }
            tabOrder.setSelectedIndex(1);
            loadtable();
        } catch (Exception e) {
            DialogHelper.alert(this, "Đã có số order này");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        listobj.clear();
        loadtable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        listobj.remove(tblBill.getSelectedRow());
        loadtable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dashboard frmD = new Dashboard();
        frmD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    DrinksDAO drdao = new DrinksDAO();
    List<Drinks> list = drdao.ShowDrinks("");

    void load() {
        pnlMenu.removeAll();
        pnlCate.removeAll();
        for (Drinks dr : list) {
            KButton btn = new KButton();
            btn.setSize(100, 100);
            btn.setPreferredSize(new Dimension(155, 30));
            btn.setkEndColor(new java.awt.Color(67, 67, 67));
            btn.setkStartColor(new java.awt.Color(0, 0, 0));
            btn.setkHoverStartColor(new java.awt.Color(44, 62, 80));
            btn.setkHoverEndColor(new java.awt.Color(253, 116, 108));
            btn.setFont(new Font("Arial", Font.BOLD, 18));
            btn.setkSelectedColor(Color.GREEN);
            btn.setForeground(Color.yellow);
            btn.setName(dr.getName());
            btn.setText(dr.getName());

            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (listobj.isEmpty()) {
                        Object[] row = new Object[5];
                        row[0] = dr.getId();
                        row[1] = dr.getName();
                        row[2] = dr.getIdcategory();
                        row[3] = dr.getPrice();
                        row[4] = 1;
                        listobj.add(row);
                    } else {
                        for (Object[] object : listobj) {
                            if ((Integer) object[0] == dr.getId()) {
                                object[4] = (int) object[4] + 1;
                                loadtable();
                                return;
                            }
                        }
                        Object[] row = new Object[5];
                        row[0] = dr.getId();
                        row[1] = dr.getName();
                        row[2] = dr.getIdcategory();
                        row[3] = dr.getPrice();
                        row[4] = 1;
                        listobj.add(row);

                    }
                    loadtable();
                }
            });
            pnlMenu.add(btn);
        }
        CategoryDAO ctdao = new CategoryDAO();
        List<Category> list1 = ctdao.ShowCate("");
        for (Category ct : list1) {
            KButton btn1 = new KButton();
            btn1.setSize(100, 100);
            btn1.setPreferredSize(new Dimension(100, 100));
            btn1.setkEndColor(new java.awt.Color(67, 67, 67));
            btn1.setkStartColor(new java.awt.Color(0, 0, 0));
            btn1.setFont(new Font("Arial", Font.BOLD, 14));
            btn1.setkHoverStartColor(new java.awt.Color(44, 62, 80));
            btn1.setkHoverEndColor(new java.awt.Color(253, 116, 108));
            btn1.setkForeGround(Color.YELLOW);
            btn1.setName(String.valueOf(ct.getId()));
            btn1.setText(ct.getName());
            btn1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    list = drdao.ShowbyCate(ct.getId());
                    pnlMenu.removeAll();
                    pnlMenu.revalidate();
                    pnlMenu.repaint();
                    load();
                }
            });
            pnlCate.add(btn1);
        }
        KButton btn1 = new KButton();
        btn1.setSize(100, 100);
        btn1.setPreferredSize(new Dimension(100, 100));
        btn1.setkEndColor(new java.awt.Color(67, 67, 67));
        btn1.setkStartColor(new java.awt.Color(0, 0, 0));
        btn1.setFont(new Font("Arial", Font.BOLD, 14));
        btn1.setkHoverStartColor(new java.awt.Color(44, 62, 80));
        btn1.setkHoverEndColor(new java.awt.Color(253, 116, 108));
        btn1.setkForeGround(Color.YELLOW);
//            btn1.setName(String.valueOf(ct.getId()));
        btn1.setText("Tất cả");
        btn1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                list = drdao.ShowDrinks("");
                pnlMenu.removeAll();
                pnlMenu.revalidate();
                pnlMenu.repaint();

                load();
            }
        });
        pnlCate.add(btn1);
    }

    void loadtable() {
        DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
        model.setRowCount(0);
        total = 0;
        for (Object[] object : listobj) {
            model.addRow(object);
            String a = String.valueOf(object[3]);
            a = a.substring(0, a.length() - 2);
            total += Integer.parseInt(a) * (int) object[4];
        }
        tblBill.setModel(model);
        lbTotal.setText(String.valueOf(total) + ".000 VNĐ");
        pnlOrder.removeAll();
        pnlOrder.revalidate();
        pnlOrder.repaint();
        List<OrderNumber> listor = ordao.findbystatus(true);
        for (OrderNumber order : listor) {
            KButton btn2 = new KButton();
            btn2.setName(String.valueOf(order.getId()));
            btn2.setText(String.valueOf(order.getId()));
            btn2.setSize(100, 100);
            btn2.setPreferredSize(new Dimension(100, 100));
            btn2.setkEndColor(new java.awt.Color(67, 67, 67));
            btn2.setkStartColor(new java.awt.Color(0, 0, 0));
            btn2.setFont(new Font("Arial", Font.BOLD, 14));
            btn2.setkHoverStartColor(new java.awt.Color(44, 62, 80));
            btn2.setkHoverEndColor(new java.awt.Color(253, 116, 108));
            btn2.setkForeGround(Color.YELLOW);
            btn2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        listbill.clear();
                        String sql = "select idbill,Drinks.name,BillInfo.Quantity,BillInfo.Price from BillInfo,Drinks where idBill=" + bdao.maxbill(order.getId()) + " and BillInfo.idDrinks=Drinks.id";
                        ResultSet rs = JdbcHelper.executeQuery(sql);
                        while (rs.next()) {
                            Object[] row = new Object[4];
                            row[0] = rs.getString("name");
                            row[1] = rs.getInt("Quantity");
                            row[2] = rs.getInt("Price");
                            row[3] = rs.getInt("idbill");
                            listbill.add(row);
                        }
                        PrinterJob pj = PrinterJob.getPrinterJob();
                        pj.setPrintable(new BillPrintable(), getPageFormat(pj));
                        try {
                            pj.print();

                        } catch (PrinterException ex) {
                            ex.printStackTrace();
                        }
                        listbill.clear();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    order.setStatus(false);
                    ordao.Update(order);
                    loadtable();
                }
            });
            pnlOrder.add(btn2);
        }
    }

    protected static double convert_CM_To_PPI(double cm) {
        return toPPI(cm * 0.393600787);
    }

    protected static double toPPI(double inch) {
        return inch * 72d;
    }

    public PageFormat getPageFormat(PrinterJob pj) {
        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();
        double middleHeight = 8.0;
        double headerHeight = 2.0;
        double footerHeight = 2.0;
        double width = convert_CM_To_PPI(8);      //printer know only point per inch.default value is 72ppi
        double height = convert_CM_To_PPI(headerHeight + middleHeight + footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(
                0,
                10,
                width,
                height - convert_CM_To_PPI(1)
        );   //define boarder size    after that print area width is about 180 points
        pf.setOrientation(PageFormat.PORTRAIT);           //select orientation portrait or landscape but for this time portrait
        pf.setPaper(paper);
        return pf;
    }

    public class BillPrintable implements Printable {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                throws PrinterException {
            int result = NO_SUCH_PAGE;
            if (pageIndex == 0) {
                Graphics2D g2d = (Graphics2D) graphics;
                double width = pageFormat.getImageableWidth();
                g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());
                ////////// code by alqama//////////////
                FontMetrics metrics = g2d.getFontMetrics(new Font("Arial", Font.BOLD, 7));
                //    int idLength=metrics.stringWidth("000000");
                //int idLength=metrics.stringWidth("00");
                int idLength = metrics.stringWidth("000");
                int amtLength = metrics.stringWidth("000000");
                int qtyLength = metrics.stringWidth("00000");
                int priceLength = metrics.stringWidth("000000");
                int prodLength = (int) width - idLength - amtLength - qtyLength - priceLength - 17;
                //    int idPosition=0;
                //    int productPosition=idPosition + idLength + 2;
                //    int pricePosition=productPosition + prodLength +10;
                //    int qtyPosition=pricePosition + priceLength + 2;
                //    int amtPosition=qtyPosition + qtyLength + 2;
                int productPosition = 0;
                int discountPosition = prodLength + 5;
                int pricePosition = discountPosition + idLength + 10;
                int qtyPosition = pricePosition + priceLength + 4;
                int amtPosition = qtyPosition + qtyLength;
                try {
                    /*Draw Header*/
                    int y = 20;
                    int yShift = 10;
                    int headerRectHeight = 15;
                    int headerRectHeighta = 40;

                    ///////////////// Product names Get ///////////
//                    String pn1a = pn1.getText();
//                    String pn2a = pn2.getText();
//                    String pn3a = pn3.getText();
//                    String pn4a = pn4.getText();
                    ///////////////// Product names Get ///////////
                    ///////////////// Product price Get ///////////
//                    int pp1a = Integer.valueOf(pp1.getText());
//                    int pp2a = Integer.valueOf(pp2.getText());
//                    int pp3a = Integer.valueOf(pp3.getText());
//                    int pp4a = Integer.valueOf(pp4.getText());
//                    int sum = pp1a + pp2a + pp3a + pp4a;
                    ///////////////// Product price Get ///////////
                    Object[] ob = listbill.get(0);
                    int sum = 0;
                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawString("-------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString("        Coffe Bill Receipt        ", 12, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 12, y);
                    y += headerRectHeight;
                    g2d.drawString("       Innovation building-QTSC      ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += headerRectHeight;
                    g2d.drawString(" ID Bill:                 " + ob[3] + "   ", 10, y);
                    y += yShift;
                    g2d.drawString(" Staff Name:              " + ShareHelper.USER.getDisplayName() + "      ", 10, y);
                    y += yShift;
                    g2d.drawString(" Time:                 " + new Date() + "   ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += headerRectHeight;
                    g2d.drawString(" Drink Name       Quantity    T.Price   ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += headerRectHeight;
                    for (Object[] object : listbill) {
                        String a = " ";
                        int b = 21 - object[0].toString().length();
                        a += object[0];
                        for (int j = 0; j <= b; j++) {
                            a += " ";
                        }
                        a += object[1];
                        for (int p = 0; p <= 8; p++) {
                            a += " ";
                        }
                        a += object[2];
                        g2d.drawString(a, 10, y);//" " + object[0] + "      " + object[1] + "        " + object[2] + "  "
                        y += yShift;
                        sum += (int) object[2];
                    }
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString(" Total amount: " + sum + ".000 VND               ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString("          Free Home Delivery         ", 10, y);
                    y += yShift;
                    g2d.drawString("             0938009421              ", 10, y);
                    y += yShift;
                    g2d.drawString("*************************************", 10, y);
                    y += yShift;
                    g2d.drawString("    THANKS TO VISIT OUR COFFE SHOP   ", 10, y);
                    y += yShift;
                    g2d.drawString("*************************************", 10, y);
                    y += yShift;

//            g2d.setFont(new Font("Monospaced",Font.BOLD,10));
//            g2d.drawString("Customer Shopping Invoice", 30,y);y+=yShift; 
                } catch (Exception r) {
                    r.printStackTrace();
                }

                result = PAGE_EXISTS;
            }
            return result;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbl22222;
    private javax.swing.JLabel lblname;
    private javax.swing.JPanel pnlCate;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JTabbedPane tabOrder;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtOrderNumber;
    // End of variables declaration//GEN-END:variables
}
